global:
  resolve_timeout: 5m

route:
  receiver: discord
  group_by: ['alertname','severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: discord
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1507397600121323670/zoZ4dgChN_VMDdoWBTHJ_lmi0ZAvdxFFlCY6JIX0-xNHB3Ni8U1TeHr5-7Wa2JsdV45F/slack'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname','instance']